insert into TO_DO (ID,USER_NAME,DESCRIPTION,TARGET_DATE,DONE)
VALUES(10001,'SOURABH','LEARN AWS CLOUD',CURRENT_DATE(),'FALSE');

insert into TO_DO (ID,USER_NAME,DESCRIPTION,TARGET_DATE,DONE)
VALUES(10002,'SOURABH','LEARN AZURE CLOUD',CURRENT_DATE(),'FALSE');

insert into TO_DO (ID,USER_NAME,DESCRIPTION,TARGET_DATE,DONE)
VALUES(10003,'SOURABH','LEARN GCP CLOUD',CURRENT_DATE(),'FALSE');

insert into TO_DO (ID,USER_NAME,DESCRIPTION,TARGET_DATE,DONE)
VALUES(10004,'SOURABH','LEARN DEVOPS',CURRENT_DATE(),'FALSE');